# Generated by Django 5.1 on 2024-11-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0003_alter_lesson_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=10, verbose_name='Payment Method')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='courses.course', verbose_name='Paid Course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lessons.lesson', verbose_name='Paid Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
